image:
  repository: sahuasmit15/go-web-app
  pullPolicy: IfNotPresent
  tag: "29339448063"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
